In [1]:
import numpy as np

In [5]:
2 + 3

5

In [6]:
for i in range(5):
    print(i)

0
1
2
3
4


In [7]:
a = [0, 1, 2, 3, 4, "ee"]
for i in a:
    print(i)

0
1
2
3
4
ee


In [8]:
print(range(1,6,2))

range(1, 6, 2)


In [9]:
arr = np.arange(6)

In [10]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
for i in arr:
    print(i)

0
1
2
3
4
5


# Creating a list of 1000 numbers

In [12]:
my_list = []
print(my_list)
for i in range(5):
    my_list.append(i)
    print(my_list)

[]
[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]


In [13]:
my_np_list = np.arange(5)
print(my_np_list)

[0 1 2 3 4]


# Creating Number Datasets using Numpy

In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [15]:
my_list = [1, 2, 3, 4, 5, 6]
a = np.array(my_list)
a

array([1, 2, 3, 4, 5, 6])

# Creating a matrix

In [16]:
m = [
    1, 2, 3,
    4, 5, 6,
    7, 8, 9
]

In [17]:
m

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
m_1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [28]:
m_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
np_m = np.arange(1, 10)
np_m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np_m.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Addition of Matrix using Numpy Arrays

In [32]:
matrix_1 = np.arange(1, 10).reshape(3, 3)
matrix_2 = np.arange(10, 100, 10).reshape(3, 3)

In [33]:
matrix_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
matrix_2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [35]:
matrix_1 + matrix_2

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

# Addition of Matrix using Python Lists


In [62]:
matrix_3 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
matrix_4 = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [63]:
matrix_3

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [64]:
matrix_4

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [66]:
matrix_3 + matrix_4

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 50, 60, 70, 80, 90]